import { Menu } from './menu';

export const MenuList: Menu[] = [
  { id: 10, name: "白州",　cat1: "whiskey", cat2: "Japanese", cat3: "single-malt" , image: "../../assets/image/whiskey/jpn/hakushu.png", sentence: "白州の"},
  { id: 11, name: "山崎",　cat1: "whiskey", cat2: "Japanese", cat3: "single-malt" , image: "../../assets/image/whiskey/jpn/yamazaki.jpg", sentence: "白州の"},
  { id: 12, name: "宮城峡",　cat1: "whiskey", cat2: "Japanese", cat3: "single-malt" , image: "../../assets/image/whiskey/jpn/miyagikyou.jpg", sentence: "白州の"},
  { id: 13, name: "West Cork 10y",　cat1: "whiskey", cat2: "Irish", cat3: "" , image: "../../assets/image/whiskey/irish/westcork10.jpg", sentence: "初めて買ったアイリッシュウイスキー。これがアイリッシュの特徴？？もっといろいろ試してみなければ"},
  { id: 14, name: "Makers Mark",　cat1: "whiskey", cat2: "Bourbon", cat3: "" , image: "../../assets/image/whiskey/bourbon/makersmark.jpg", sentence: "溶かした蝋にボトルを漬けて、一つ一つ手作業で封蝋していることで有名な日本でも最近有名になって来たバーボン。原料に小麦を使っているので他のバーボンよりも柔らかい口当たりが特徴。"},
  { id: 15, name: "Old Crow",　cat1: "whiskey", cat2: "Bourbon", cat3: "" , image: "../../assets/image/whiskey/bourbon/oldcrow.jpg", sentence: "白州の"},
  { id: 16, name: "Woodford Reserve",　cat1: "whiskey", cat2: "Bourbon", cat3: "" , image: "../../assets/image/whiskey/bourbon/woodford_reserve.jpg", sentence: "白州の"},
  { id: 17, name: "Wild Turkey 8y",　cat1: "whiskey", cat2: "Bourbon", cat3: "" , image: "../../assets/image/whiskey/bourbon/wildturkey_8y.jpg", sentence: "最初に買ったバーボンで力強く男くささが特徴。これとスコッチを飲み比べてバーボンの味を覚えた。"},
  { id: 18, name: "Ardmore Legacy",　cat1: "whiskey", cat2: "Scotch", cat3: "single-malt" , image: "../../assets/image/whiskey/scotch/ardmore_legacy.jpg", sentence: "白州の"},
  { id: 19, name: "Ballantines 12y",　cat1: "whiskey", cat2: "Scotch", cat3: "blended" , image: "../../assets/image/whiskey/scotch/ballantines_12.png", sentence: "確か自分で買った最初のウイスキー。ウイスキーのスモーキーとはを学んだ。"},
  { id: 20, name: "Ballantines finest",　cat1: "whiskey", cat2: "Scotch", cat3: "blended" , image: "../../assets/image/whiskey/scotch/ballantines_finest.png", sentence: "安い。家で気軽にスコッチ系のハイボールを作って飲むならこれがいいなと思う。"},
  { id: 21, name: "Chivas Regal 12y",　cat1: "whiskey", cat2: "Scotch", cat3: "blended" , image: "../../assets/image/whiskey/scotch/chivas_regal12.png", sentence: "白州の"},
  { id: 22, name: "Glenfarclas 105",　cat1: "whiskey", cat2: "Scotch", cat3: "single-malt" , image: "../../assets/image/whiskey/scotch/glenfarclas105.jpg", sentence: "百貨店で売り子の人が売っていたので買ったグレンファークラス。実際買ったのは原酒（アルコール60度くらいだった）のやつ。"},
  { id: 23, name: "Glenfiddich 12y",　cat1: "whiskey", cat2: "Scotch", cat3: "single-malt" , image: "../../assets/image/whiskey/scotch/glenfiddich_12.jpg", sentence: "甘い香りが特徴のグレンフィディック。"},
  { id: 24, name: "Glengoyne",　cat1: "whiskey", cat2: "Scotch", cat3: "single-malt" , image: "../../assets/image/whiskey/scotch/glengoyne.jpg", sentence: "どっしりシェリーなやつを買いたいと思って色々調べた結果にかったグレンゴイン。シェリーとはこのことかと学んだ。"},
  { id: 25, name: "Laphroaig select",　cat1: "whiskey", cat2: "Scotch", cat3: "single-malt" , image: "../../assets/image/whiskey/scotch/laphroaig_select.jpg", sentence: "アイラの中でもピート香が最高級に強い。最初飲んだ時は正露丸を連想した。正露丸自体は飲んだことないのになぜか正露丸を連想した。"},
  { id: 26, name: "Bass ペールエール",　cat1: "others", cat2: "Beer", cat3: "" , image: "../../assets/image/whiskey/scotch/laphroaig_select.jpg", sentence: "白州の"},
  { id: 27, name: "プレミアムモルツ",　cat1: "others", cat2: "Beer", cat3: "" , image: "../../assets/image/whiskey/scotch/laphroaig_select.jpg", sentence: "白州の"},
  { id: 28, name: "季節のノンアルコールカクテル",　cat1: "non-alcohol", cat2: "Non-alcohol-cocktail", cat3: "" , image: "../../assets/image/whiskey/scotch/laphroaig_select.jpg", sentence: "白州の"},
  { id: 29, name: "魔法の水",　cat1: "non-alcohol", cat2: "Non-alcohol-cocktail", cat3: "" , image: "../../assets/image/whiskey/scotch/laphroaig_select.jpg", sentence: "白州の"},
  { id: 30, name: "ナッツ",　cat1: "food", cat2: "", cat3: "" , image: "../../assets/image/whiskey/scotch/laphroaig_select.jpg", sentence: "白州の"},
  { id: 31, name: "まさかのカレーライス",　cat1: "food", cat2: "", cat3: "" , image: "../../assets/image/whiskey/scotch/laphroaig_select.jpg", sentence: "みんな大好きカレーライス！ウイスキーとの愛称は絶望的！"},
  { id: 32, name: "クラムチャウダー",　cat1: "food", cat2: "", cat3: "" , image: "../../assets/image/whiskey/scotch/laphroaig_select.jpg", sentence: "白州の"},
];
