import { Menu } from './menu';

export const MenuList: Menu[] = [
  { id: 10, name: "白州",　cat1: "whiskey", cat2: "Japan", cat3: "single-malt" , image: "../../assets/image/whiskey/jpn/hakusyu.png", sentence: "白州の"},
  { id: 11, name: "山崎",　cat1: "whiskey", cat2: "Japan", cat3: "single-malt" , image: "../../assets/image/whiskey/jpn/yamazaki.jpg", sentence: "白州の"},
  { id: 12, name: "宮城峡",　cat1: "whiskey", cat2: "Japan", cat3: "single-malt" , image: "../../assets/image/whiskey/jpn/miyagikyou.jpg", sentence: "白州の"},
  { id: 13, name: "West Cork 10y",　cat1: "whiskey", cat2: "Irish", cat3: "single-malt" , image: "../../assets/image/whiskey/irish/westcork10.jpg", sentence: "白州の"},
  { id: 14, name: "Makers Mark",　cat1: "whiskey", cat2: "Bourbon", cat3: "single-malt" , image: "../../assets/image/whiskey/bourbon/makersmark.jpg", sentence: "白州の"},
  { id: 15, name: "Old Crow",　cat1: "whiskey", cat2: "Bourbon", cat3: "single-malt" , image: "../../assets/image/whiskey/bourbon/oldcrow.jpg", sentence: "白州の"},
  { id: 16, name: "Woodford Reserve",　cat1: "whiskey", cat2: "Bourbon", cat3: "single-malt" , image: "../../assets/image/whiskey/bourbon/oldcrow.jpg", sentence: "白州の"},
  { id: 17, name: "Old Crow",　cat1: "whiskey", cat2: "Bourbon", cat3: "single-malt" , image: "../../assets/image/whiskey/bourbon/oldcrow.jpg", sentence: "白州の"},
  { id: 18, name: "Ardmore Legacy",　cat1: "whiskey", cat2: "Scotch", cat3: "single-malt" , image: "../../assets/image/whiskey/scotch/ardmore.jpg", sentence: "白州の"},
  { id: 19, name: "Ballantines 12y",　cat1: "whiskey", cat2: "Scotch", cat3: "blended" , image: "../../assets/image/whiskey/scotch/ballentines_12.png", sentence: "白州の"},
  { id: 20, name: "Ballantines finest",　cat1: "whiskey", cat2: "Scotch", cat3: "blended" , image: "../../assets/image/whiskey/scotch/ballentines_finest.png", sentence: "白州の"},
  { id: 21, name: "Chivas Regal 12",　cat1: "whiskey", cat2: "Scotch", cat3: "blended" , image: "../../assets/image/whiskey/scotch/chivas_regal12.png", sentence: "白州の"},
  { id: 22, name: "Glenfarclas 105",　cat1: "whiskey", cat2: "Scotch", cat3: "single-malt" , image: "../../assets/image/whiskey/scotch/glenfarclas105.png", sentence: "白州の"},
  { id: 23, name: "Glenfiddich_12",　cat1: "whiskey", cat2: "Scotch", cat3: "single-malt" , image: "../../assets/image/whiskey/scotch/glenfiddich_12.jpg", sentence: "白州の"},
  { id: 24, name: "Glengoyne",　cat1: "whiskey", cat2: "Scotch", cat3: "single-malt" , image: "../../assets/image/whiskey/scotch/glengoyne.jpg", sentence: "白州の"},
  { id: 25, name: "Laphroaig_select",　cat1: "whiskey", cat2: "Scotch", cat3: "single-malt" , image: "../../assets/image/whiskey/scotch/laphroaig_select.jpg", sentence: "白州の"},
  { id: 26, name: "Bass ペールエール",　cat1: "others", cat2: "Beer", cat3: "" , image: "../../assets/image/whiskey/scotch/laphroaig_select.jpg", sentence: "白州の"},
  { id: 27, name: "プレミアムモルツ",　cat1: "others", cat2: "Beer", cat3: "" , image: "../../assets/image/whiskey/scotch/laphroaig_select.jpg", sentence: "白州の"},
  { id: 28, name: "季節のノンアルコールカクテル",　cat1: "non-alcohol", cat2: "Non-alcohol-cocktail", cat3: "" , image: "../../assets/image/whiskey/scotch/laphroaig_select.jpg", sentence: "白州の"},
  { id: 29, name: "魔法の水",　cat1: "non-alcohol", cat2: "Non-alcohol-cocktail", cat3: "" , image: "../../assets/image/whiskey/scotch/laphroaig_select.jpg", sentence: "白州の"},
  { id: 30, name: "ナッツ",　cat1: "food", cat2: "", cat3: "" , image: "../../assets/image/whiskey/scotch/laphroaig_select.jpg", sentence: "白州の"},
  { id: 31, name: "まさかのカレーライス",　cat1: "food", cat2: "", cat3: "" , image: "../../assets/image/whiskey/scotch/laphroaig_select.jpg", sentence: "みんな大好きカレーライス！ウイスキーとの愛称は絶望的！"},
  { id: 32, name: "クラムチャウダー",　cat1: "food", cat2: "", cat3: "" , image: "../../assets/image/whiskey/scotch/laphroaig_select.jpg", sentence: "白州の"},
];
